/**
 * @docfonts/registry - the source of truth for docfonts evidence, plus the corpus + measurement
 * provenance schemas. Three artifact layers live in ./types; ./schema validates the public records.
 *
 * Boundary: composes parsed facts (@docfonts/font-metadata, TYPE-only) and verdicts (@docfonts/core).
 * It does NOT parse fonts or DOCX, and does NOT score - it stores results and answers queries. The
 * corpus / measurements / records live as versioned JSON under ./data, produced by
 * scripts/import-research.ts. Query helpers here are pure and take the loaded records as input.
 */

export {
  EVIDENCE_RECORDS_SCHEMA,
  type ValidateOptions,
  type ValidationResult,
  validateRecords,
} from "./schema";
export type {
  AnalyticAdvanceMeasurement,
  BrowserCanvasMeasurement,
  CandidateFaceId,
  CandidateRef,
  CandidateScore,
  CorpusFace,
  CorpusFamily,
  CorpusId,
  CorpusManifest,
  EvidenceId,
  EvidenceRecord,
  FaceAggregateMeasurement,
  Gates,
  LayoutProof,
  LiveLayoutMeasurement,
  MeasurementId,
  MeasurementKind,
  MeasurementResult,
  TopCandidatesMeasurement,
} from "./types";

import recordsData from "../data/registry/records.json";
import { SEED_RECORDS } from "./seed";
import type { EvidenceRecord } from "./types";

/**
 * The CANONICAL public registry, loaded from data/registry/records.json. That file is GENERATED by
 * scripts/import-research.ts from the corpus + measurements - never hand-seeded - and is EMPTY until
 * the importer runs. This function never falls back to the seed: an empty result means the importer
 * has not run yet. Validate with validateRecords (optionally against the measurement set) before use.
 */
export function loadRecords(): EvidenceRecord[] {
  return recordsData as unknown as EvidenceRecord[];
}

/**
 * The INTERIM research/bootstrap seed (see ./seed). NOT canonical - it lets the site render real
 * measured rows before scripts/import-research.ts materializes the registry. Callers opt in
 * explicitly (so the temporary dependency is visible); it is not a silent fallback of loadRecords().
 */
export function loadSeedRecords(): EvidenceRecord[] {
  return SEED_RECORDS;
}

/** Evidence records whose originalFont matches `name`, case-insensitive. Pure. */
export function findByOriginal(
  records: readonly EvidenceRecord[],
  name: string,
): EvidenceRecord[] {
  const key = name.toLowerCase();
  return records.filter((r) => r.originalFont.toLowerCase() === key);
}

/** Evidence records carrying a given verdict. Pure. */
export function withVerdict(
  records: readonly EvidenceRecord[],
  verdict: EvidenceRecord["verdict"],
): EvidenceRecord[] {
  return records.filter((r) => r.verdict === verdict);
}
