/**
 * @docfonts/registry - the source of truth for docfonts evidence, plus the corpus + measurement
 * provenance schemas. Three artifact layers live in ./types; ./schema validates the public records.
 *
 * Boundary: composes parsed facts (@docfonts/font-metadata, TYPE-only) and verdicts (@docfonts/core).
 * It does NOT parse fonts or DOCX, and does NOT score - it stores results and answers queries. The
 * corpus / measurements / records live as versioned JSON under ./data, produced by
 * scripts/import-research.ts. Query helpers here are pure and take the loaded records as input.
 */

export {
  EVIDENCE_RECORDS_SCHEMA,
  type ValidateOptions,
  type ValidationResult,
  validateRecords,
} from "./schema";
export type {
  AnalyticAdvanceMeasurement,
  BrowserCanvasMeasurement,
  CandidateFaceId,
  CandidateRef,
  CandidateScore,
  CorpusFace,
  CorpusFamily,
  CorpusId,
  CorpusManifest,
  EvidenceId,
  EvidenceRecord,
  FaceAggregateMeasurement,
  Gates,
  LayoutProof,
  LiveLayoutMeasurement,
  MeasurementId,
  MeasurementKind,
  MeasurementResult,
  TopCandidatesMeasurement,
} from "./types";

import shipSetCorpus from "../data/corpus/current-ship-set-2026-06-03.json";
import recordsData from "../data/registry/records.json";
import type { CorpusManifest, EvidenceRecord } from "./types";

/**
 * The CANONICAL public registry, loaded from data/registry/records.json. That file is GENERATED by
 * scripts/import-research.ts from the corpus + measurements - never hand-seeded. Validate with
 * validateRecords (optionally against the measurement set) before use.
 */
export function loadRecords(): EvidenceRecord[] {
  return recordsData as unknown as EvidenceRecord[];
}

/**
 * The open-font CORPUS manifests (provenance + parsed facts + hashes; no binaries). GENERATED by
 * scripts/import-corpus.ts from SuperDoc ship-set / open-font packets. The durable join key from an
 * EvidenceRecord candidate to a corpus face is fileSha256. First slice: the current ship-set only.
 */
export function loadCorpus(): CorpusManifest[] {
  return [shipSetCorpus as unknown as CorpusManifest];
}

/** All corpus faces across every manifest, flattened with their family. Pure. */
export function corpusFaces(manifests: readonly CorpusManifest[]) {
  return manifests.flatMap((m) =>
    m.families.flatMap((fam) =>
      fam.faces.map((face) => ({ family: fam, face })),
    ),
  );
}

/** Evidence records whose originalFont matches `name`, case-insensitive. Pure. */
export function findByOriginal(
  records: readonly EvidenceRecord[],
  name: string,
): EvidenceRecord[] {
  const key = name.toLowerCase();
  return records.filter((r) => r.originalFont.toLowerCase() === key);
}

/** Evidence records carrying a given verdict. Pure. */
export function withVerdict(
  records: readonly EvidenceRecord[],
  verdict: EvidenceRecord["verdict"],
): EvidenceRecord[] {
  return records.filter((r) => r.verdict === verdict);
}
