/**
 * INTERIM research/bootstrap seed - NOT the source of truth.
 *
 * The canonical public registry is data/registry/records.json, GENERATED by
 * scripts/import-research.ts from the corpus + measurements. Until that importer runs, the site
 * consumes this seed EXPLICITLY via loadSeedRecords() (never as a silent fallback from loadRecords()).
 * When the importer lands, records.json becomes non-empty and the site switches to loadRecords().
 *
 * Carried from font-fidelity-research (STATUS.csv + scorecard 2026-06-03 + word-font-decision-catalog).
 * Typed as EvidenceRecord[], so it is validated at COMPILE time. Every gate value mirrors the research
 * STATUS.csv; every advance number is measured (analytic-hmtx), not asserted. Rows whose layout gate is
 * "pass" reference a face_aggregate proof (the all-faces layout proof recorded in research); those
 * proof artifacts are materialized by the importer.
 */
import type { EvidenceRecord } from "./types";

export const SEED_RECORDS: EvidenceRecord[] = [
  {
    evidenceId: "calibri",
    originalFont: "Calibri",
    candidate: { candidateFamily: "Carlito" },
    verdict: "metric_safe",
    faces: { regular: true, bold: true, italic: true, boldItalic: true },
    advance: { meanDelta: 0, maxDelta: 0 },
    candidateLicense: "OFL-1.1",
    candidateLicenseSource:
      "font-fidelity-research scorecard 2026-06-03 (google/fonts ofl/carlito)",
    gates: { static: "pass", metric: "pass", layout: "pass", ship: "pass" },
    measurementRefs: [
      "calibri__carlito#analytic_advance#2026-06-03",
      "calibri__carlito#face_aggregate#2026-06-03",
    ],
    policyAction: "substitute",
    confidence: "high",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "Advance 0.00% (analytic-hmtx). All four faces layout-proven vs Word; shipped in SuperDoc.",
  },
  {
    evidenceId: "arial",
    originalFont: "Arial",
    candidate: { candidateFamily: "Liberation Sans" },
    verdict: "metric_safe",
    faces: { regular: true, bold: true, italic: true, boldItalic: true },
    advance: { meanDelta: 0, maxDelta: 0 },
    candidateLicense: "OFL-1.1",
    candidateLicenseSource:
      "font-fidelity-research scorecard 2026-06-03 (RedHat liberation-fonts)",
    gates: { static: "pass", metric: "pass", layout: "not_run", ship: "pass" },
    measurementRefs: ["arial__liberation-sans#analytic_advance#2026-06-03"],
    policyAction: "substitute",
    confidence: "high",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "Advance 0.00% (analytic-hmtx); shipped in SuperDoc. Individual full-page layout proof not yet run.",
  },
  {
    evidenceId: "times-new-roman",
    originalFont: "Times New Roman",
    candidate: { candidateFamily: "Liberation Serif" },
    verdict: "metric_safe",
    faces: { regular: true, bold: true, italic: true, boldItalic: true },
    advance: { meanDelta: 0, maxDelta: 0 },
    candidateLicense: "OFL-1.1",
    candidateLicenseSource:
      "font-fidelity-research scorecard 2026-06-03 (RedHat liberation-fonts)",
    gates: { static: "pass", metric: "pass", layout: "not_run", ship: "pass" },
    measurementRefs: [
      "times-new-roman__liberation-serif#analytic_advance#2026-06-03",
    ],
    policyAction: "substitute",
    confidence: "high",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "Advance 0.00% (analytic-hmtx); shipped in SuperDoc. Individual full-page layout proof not yet run.",
  },
  {
    evidenceId: "courier-new",
    originalFont: "Courier New",
    candidate: { candidateFamily: "Liberation Mono" },
    verdict: "metric_safe",
    faces: { regular: true, bold: true, italic: true, boldItalic: true },
    advance: { meanDelta: 0, maxDelta: 0 },
    candidateLicense: "OFL-1.1",
    candidateLicenseSource:
      "font-fidelity-research scorecard 2026-06-03 (RedHat liberation-fonts)",
    gates: { static: "pass", metric: "pass", layout: "not_run", ship: "pass" },
    measurementRefs: [
      "courier-new__liberation-mono#analytic_advance#2026-06-03",
    ],
    policyAction: "substitute",
    confidence: "high",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "Advance 0.00% (analytic-hmtx); shipped in SuperDoc. Individual full-page layout proof not yet run.",
  },
  {
    evidenceId: "cambria",
    originalFont: "Cambria",
    candidate: { candidateFamily: "Caladea" },
    verdict: "metric_safe",
    faces: { regular: true, bold: true, italic: true, boldItalic: true },
    advance: { meanDelta: 0.0001, maxDelta: 0.0005 },
    candidateLicense: "Apache-2.0",
    candidateLicenseSource:
      "font-fidelity-research scorecard 2026-06-03 (Fedora google-crosextra-caladea)",
    gates: { static: "pass", metric: "pass", layout: "not_run", ship: "pass" },
    measurementRefs: ["cambria__caladea#analytic_advance#2026-06-03"],
    policyAction: "substitute",
    confidence: "high",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "Advance within direct threshold (analytic-hmtx); shipped in SuperDoc. Individual full-page layout proof not yet run.",
  },
  {
    evidenceId: "georgia",
    originalFont: "Georgia",
    candidate: { candidateFamily: "Gelasio" },
    verdict: "metric_safe",
    faces: { regular: true, bold: true, italic: true, boldItalic: true },
    advance: { meanDelta: 0, maxDelta: 0 },
    candidateLicense: "OFL-1.1",
    candidateLicenseSource:
      "font-fidelity-research scorecard 2026-06-03 (SorkinType/Gelasio)",
    gates: { static: "pass", metric: "pass", layout: "pass", ship: "fail" },
    measurementRefs: [
      "georgia__gelasio#analytic_advance#2026-06-03",
      "georgia__gelasio#face_aggregate#2026-06-03",
    ],
    policyAction: "substitute",
    confidence: "high",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "Advance 0.00% (analytic-hmtx). All four faces layout-proven vs Word (2026-06-03). Ship blocked on legal sign-off (Gelasio OFL), not on layout.",
  },
  {
    evidenceId: "arial-narrow",
    originalFont: "Arial Narrow",
    candidate: { candidateFamily: "Liberation Sans Narrow" },
    verdict: "metric_safe",
    faces: { regular: true, bold: true, italic: true, boldItalic: true },
    advance: { meanDelta: 0, maxDelta: 0 },
    candidateLicense: "GPLv2-with-font-exception",
    candidateLicenseSource:
      "font-fidelity-research scorecard 2026-06-03 (RedHat liberation-fonts)",
    gates: { static: "pass", metric: "pass", layout: "pass", ship: "fail" },
    measurementRefs: [
      "arial-narrow__liberation-sans-narrow#analytic_advance#2026-06-03",
      "arial-narrow__liberation-sans-narrow#face_aggregate#2026-06-03",
    ],
    policyAction: "substitute",
    confidence: "high",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "Advance 0.00% (analytic-hmtx). All four faces layout-proven vs Word (2026-06-03). Ship blocked on legal review (GPLv2 font exception), not on layout.",
  },
  {
    evidenceId: "comic-sans-ms",
    originalFont: "Comic Sans MS",
    candidate: { candidateFamily: "Comic Neue" },
    verdict: "visual_only",
    faces: { regular: false, bold: false, italic: false, boldItalic: false },
    advance: { meanDelta: 0.0973, maxDelta: 0.1384 },
    candidateLicense: "OFL-1.1",
    candidateLicenseSource:
      "font-fidelity-research scorecard 2026-06-03 (google/fonts ofl/comicneue)",
    gates: { static: "pass", metric: "fail", layout: "not_run", ship: "fail" },
    measurementRefs: ["comic-sans-ms__comic-neue#analytic_advance#2026-06-03"],
    policyAction: "category_fallback",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "Advance too far for metric fidelity (mean 9.73%, max 13.84%); category-correct visual fallback only. Per-face metric coverage not assessed for a category fallback.",
  },
  {
    evidenceId: "aptos",
    originalFont: "Aptos",
    candidate: null,
    verdict: "no_substitute",
    faces: { regular: false, bold: false, italic: false, boldItalic: false },
    gates: {
      static: "not_run",
      metric: "fail",
      layout: "not_run",
      ship: "fail",
    },
    measurementRefs: ["aptos#top_candidates#2026-06-03"],
    policyAction: "customer_supplied",
    exportRule: "preserve_original_name",
    measuredDate: "2026-06-03",
    notes:
      "No open metric clone (measured 2026-06-03, analytic-hmtx). Closest open font is Source Sans 3, a visual fallback only (advance 2.84% mean / 6.96% max), which reflows. Policy: customer-supplied first, else a reported visual/category fallback.",
  },
];
