/**
 * @docfonts/registry artifact schemas. Three layers, kept strictly separate:
 *   - CorpusManifest    = PROVENANCE (which open candidate files exist, from where, under what license)
 *   - MeasurementResult = PROOF (the measured numbers + raw layout detail; one type, many kinds)
 *   - EvidenceRecord    = the PUBLIC VERDICT (derived status only; points at proof by ID)
 *
 * Durable identity is by stable ID + file sha256, never by file path. The public EvidenceRecord must
 * not become a dump of proof artifacts: raw page counts / break arrays live in a LiveLayoutMeasurement.
 */
import type {
  AdvanceDelta,
  FaceCoverage,
  GateStatus,
  PolicyAction,
  Verdict,
} from "@docfonts/core";
import type {
  FontCategory,
  FontFaceMetadata,
  StyleKey,
} from "@docfonts/font-metadata";

// --- stable artifact IDs (file paths can change; these do not) ---
export type CorpusId = string; // e.g. "google-fonts-2026-06-04"
export type CandidateFaceId = string; // a specific open face, e.g. "carlito#bold" (+ sha-derived)
export type MeasurementId = string; // e.g. "calibri__carlito#analytic_advance#2026-06-03"
export type EvidenceId = string; // e.g. "calibri"

// ===========================================================================
// Layer 1 - CorpusManifest: open-candidate provenance + parsed facts
// ===========================================================================

/** One open font FACE in the corpus (a family has many). Denormalized keys for querying. */
export interface CorpusFace {
  candidateFaceId: CandidateFaceId;
  family: string;
  styleKey: StyleKey; // regular | bold | italic | boldItalic | other
  weight: number; // OS/2 usWeightClass
  style: "normal" | "italic";
  fileName: string;
  /** sha256 of the file bytes: the durable join key to measurements. */
  fileSha256: string;
  /** when this face was generated by instancing a variable font, how (else absent: a static source). */
  instancedFrom?: VariableInstanceProvenance;
  /** parsed facts (from @docfonts/font-metadata); the corpus stores facts, never scores. */
  metadata: FontFaceMetadata;
}

/**
 * Provenance for a face GENERATED by instancing a variable font (e.g. Gelasio Bold = the Gelasio[wght]
 * VF instanced at wght=700). The corpus does not instance variable fonts itself; this records how a
 * trusted reference tool produced the measured file, so it is reproducible. The face's fileSha256 is
 * the generated file; sourceFileSha256 here is the variable source.
 */
export interface VariableInstanceProvenance {
  sourceFamily: string; // e.g. "Gelasio"
  sourceFileName: string; // e.g. "Gelasio[wght].ttf"
  sourceFileSha256: string; // sha256 of the variable source font
  axes: Record<string, number>; // instanced axis coordinates, e.g. { wght: 700 }
  tool: string; // e.g. "fontTools.varLib.instancer"
  toolVersion: string; // e.g. "4.63.0"
  /** what makes the output byte-reproducible, e.g. "SOURCE_DATE_EPOCH=0 --update-name-table". */
  reproNote: string;
}

export interface CorpusFamily {
  family: string;
  license: string; // license id, e.g. "OFL-1.1"
  licenseSource: string; // provenance label for the pairing, e.g. "google/fonts ofl/carlito"
  /** sha256 of the exact license file that accompanied this source - proves file + license pairing. */
  licenseTextSha256: string;
  /** canonical URL of the license id, e.g. "http://scripts.sil.org/OFL". NOT the font source. */
  licenseUrl?: string;
  /** where the FONT files came from (source / upstream), distinct from licenseUrl. */
  sourceUrl: string;
  faces: CorpusFace[];
}

export interface CorpusManifest {
  corpusId: CorpusId;
  source: string; // e.g. "Google Fonts (Latin, all files)"
  sourceUrl: string;
  retrievedDate: string; // YYYY-MM-DD
  families: CorpusFamily[];
}

// ===========================================================================
// Layer 0 - Discovery: the SEARCH SPACE (broad inventory of open fonts we can
// compare against). DELIBERATELY distinct from the reviewed CorpusManifest above:
// "in the discovery snapshot" means only "this open font exists and is comparable",
// NOT "reviewed enough to publish". Provenance here is source-derived and lighter
// (license inferred from the source layout, commit pinned when available); it never
// carries a licenseTextSha256 and never feeds a verdict directly. A candidate is
// promoted into CorpusManifest (license-text-hashed, exact provenance) only after
// review. No font binaries are ever committed - faces are pointers (sha + re-fetch URL).
// ===========================================================================

/** A known open-font SOURCE in the source registry (data/sources.json). */
export interface FontSource {
  sourceId: string; // stable id, e.g. "google-fonts"
  name: string; // human-readable, e.g. "Google Fonts"
  type: "git" | "release" | "package" | "local-artifact";
  upstreamUrl: string; // canonical upstream, e.g. "https://github.com/google/fonts"
  /** discovery = comparable only; reviewed = vetted for evidence; authoritative = trusted to ingest directly. */
  trust: "discovery" | "reviewed" | "authoritative";
  /** how license is established for this source, e.g. "inferred from repo directory (ofl/apache/ufl)". */
  licensePolicy: string;
  retrieval: string; // how files are obtained, e.g. "raw.githubusercontent.com main branch"
  notes?: string; // public-safe notes
}

/** One face in a discovery snapshot. Shares the face FACTS with CorpusFace but carries
 *  source-derived (lighter) provenance and no parsed-from-bytes guarantee. */
export interface DiscoveryFace {
  fileSha256: string; // hex64, durable identity + re-fetch integrity check
  family: string;
  styleKey: StyleKey;
  weight: number; // default usWeightClass (variable fonts: the default instance)
  width: number; // usWidthClass
  italic: boolean;
  isVariable: boolean; // flagged explicitly; static facts describe the DEFAULT instance
  axes?: string[]; // variable axis tags, e.g. ["wght","wdth"]
  category: FontCategory; // sans | serif | mono | script | display | symbol | unknown
  latinCoverage: number; // 0..1
  fileName: string;
  repoPath: string; // path within the source (public), e.g. "ofl/roboto/Roboto[wght].ttf"
  rawUrl: string; // public re-fetch URL (the recipe; no binary committed)
  license: string; // inferred license id
  licenseBasis: string; // HOW it was inferred, e.g. "google/fonts ofl directory"
}

/** A discovery snapshot: a broad inventory of open faces. */
export interface DiscoverySnapshot {
  snapshotId: string; // e.g. "google-fonts-all-files-2026-06-04"
  sourceId: string; // FK into data/sources.json
  sourceUrl: string; // public upstream
  sourceCommit?: string; // pinned commit/tree sha when available (absent = unpinned, e.g. bootstrap)
  retrievedDate: string; // YYYY-MM-DD
  /**
   * how THIS snapshot's faces were obtained. "local_bootstrap" = mapped from an existing local corpus
   * (no fresh acquisition / pinned commit) - the bootstrap path used to validate the schema; the
   * long-term path acquires the source directly (git clone at a pinned commit, release, or package).
   */
  acquisition:
    | "local_bootstrap"
    | "git_clone"
    | "release_download"
    | "package_resolve";
  faceCount: number;
  /** duplicate fileSha256s collapsed during import, REPORTED not hidden (empty when none). */
  duplicates: { fileSha256: string; count: number }[];
  faces: DiscoveryFace[];
}

// ===========================================================================
// Layer 2 - MeasurementResult: the proof (one type, discriminated by kind)
// ===========================================================================

/** Points at what was measured. May omit the face for family-level results. */
export interface CandidateRef {
  candidateFamily: string;
  candidateFaceId?: CandidateFaceId;
  /** the exact file measured, when a specific face was used. */
  fileSha256?: string;
}

interface MeasurementBase {
  measurementId: MeasurementId;
  /** logical proprietary font name (a LABEL; no proprietary metric tables are stored). */
  originalFont: string;
  /** the oracle environment, e.g. "Windows 11 M365 Word 2026-06" - label only. */
  originalOracleEnv: string;
  /** the single candidate measured. Null/absent for negative or multi-candidate (bakeoff) results. */
  candidate?: CandidateRef | null;
  methodVersion: string;
  measuredDate: string; // YYYY-MM-DD
  testStringsRef?: string; // named test-string set
  notes?: string;
}

/** Analytic advance comparison from hmtx (no rendering). */
export interface AnalyticAdvanceMeasurement extends MeasurementBase {
  kind: "analytic_advance";
  candidate: CandidateRef; // single-pair measurement always names its candidate
  advance: AdvanceDelta;
  perFace?: Partial<Record<StyleKey, AdvanceDelta>>;
}

/** Browser / canvas measureText comparison. */
export interface BrowserCanvasMeasurement extends MeasurementBase {
  kind: "browser_canvas";
  candidate: CandidateRef;
  advance: AdvanceDelta;
  sizePx?: number;
}

/** Live Word-vs-SuperDoc layout proof. Raw proof detail lives HERE, not on the public record. */
export interface LiveLayoutMeasurement extends MeasurementBase {
  kind: "live_layout";
  candidate: CandidateRef;
  proof: LayoutProof;
}

/** Aggregate of per-face results into a family-level conclusion. */
export interface FaceAggregateMeasurement extends MeasurementBase {
  kind: "face_aggregate";
  faces: FaceCoverage;
  advance?: AdvanceDelta;
  /** the per-face measurements this aggregates. */
  components?: MeasurementId[];
}

/** A bakeoff: many candidates ranked for one original. The conclusion may still be "no substitute". */
export interface CandidateScore {
  candidate: CandidateRef;
  advance: AdvanceDelta;
  faces?: FaceCoverage;
}
export interface TopCandidatesMeasurement extends MeasurementBase {
  kind: "top_candidates";
  /** ranked best-first; empty (or all failing) is a valid "no open substitute found" result. */
  candidates: CandidateScore[];
}

export type MeasurementResult =
  | AnalyticAdvanceMeasurement
  | BrowserCanvasMeasurement
  | LiveLayoutMeasurement
  | FaceAggregateMeasurement
  | TopCandidatesMeasurement;

export type MeasurementKind = MeasurementResult["kind"];

/** Raw layout-proof detail. Belongs to a LiveLayoutMeasurement, never to the public record. */
export interface LayoutProof {
  pages: number;
  totalLines: number;
  lineBreaksMatch: boolean;
  /** 1-based line numbers whose break position diverged from Word, if any. */
  mismatchedLines?: number[];
  note?: string;
}

// ===========================================================================
// Layer 3 - EvidenceRecord: the public verdict (derived status only)
// ===========================================================================

/** Derived PUBLIC gate status. Not raw proof - the proof is in the referenced measurements. */
export interface Gates {
  static: GateStatus;
  metric: GateStatus;
  layout: GateStatus;
  ship: GateStatus;
}

/**
 * A named glyph-level advance divergence that qualifies a single face. Surfaces the honest exception
 * behind a face whose advances match everywhere EXCEPT a specific codepoint (e.g. Caladea Bold Italic
 * vs Cambria on U+0060). The full numbers live in the referenced measurement; this is the public name.
 */
export interface GlyphException {
  styleKey: StyleKey;
  codepoint: number; // the diverging glyph, e.g. 0x60 (grave accent)
  advanceDelta: number; // fractional advance divergence at this glyph (0.231 = 23.1%)
  note: string;
}

export interface EvidenceRecord {
  evidenceId: EvidenceId;
  /** logical proprietary font name; preserved for export (the substitute is render-only). */
  originalFont: string;
  /** null/absent for no_substitute / preserve_only / customer_supplied / generic policy. */
  candidate?: CandidateRef | null;
  verdict: Verdict;
  faces: FaceCoverage;
  /**
   * Per-face verdict, AUTHORITATIVE when present. Use when faces do not share one verdict - e.g. a
   * substitute that is metric-safe for most faces but only visual on one. When any faceVerdict differs
   * from the top-level `verdict`, the record is QUALIFIED: consumers must show the per-face breakdown,
   * not the top-level verdict alone, which then reads as the dominant / substitute-recommendation call.
   */
  faceVerdicts?: Partial<Record<StyleKey, Verdict>>;
  /** named glyph-level advance divergences that qualify a face (e.g. one codepoint reflows). */
  glyphExceptions?: GlyphException[];
  /** public advance summary; the full proof lives in the referenced measurements. */
  advance?: AdvanceDelta;
  candidateLicense?: string | null;
  candidateLicenseSource?: string;
  gates: Gates;
  /** proof behind this verdict, by MeasurementId (analytic + layout + ...). */
  measurementRefs: MeasurementId[];
  /** normalized, renderer-neutral action (see @docfonts/core PolicyAction). */
  policyAction?: PolicyAction;
  confidence?: string; // e.g. "R" | "high" | "medium"
  exportRule: "preserve_original_name";
  measuredDate?: string;
  notes?: string;
}
