#!/usr/bin/env bun
/**
 * gen-fallbacks-data.ts - generate packages/fallbacks/src/data.ts from the docfonts registry's reviewed
 * artifact (data/registry/substitution-evidence.json). @docfonts/fallbacks ships a typed TS const (not a
 * raw JSON import) so it is bundler-safe everywhere and carries literal types; this keeps that const in
 * lockstep with the registry. A fallbacks drift test asserts the shipped data equals the registry JSON.
 *
 * Run:  bun run scripts/gen-fallbacks-data.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SRC = join(
  import.meta.dir,
  "..",
  "packages",
  "registry",
  "data",
  "registry",
  "substitution-evidence.json",
);
const OUT = join(
  import.meta.dir,
  "..",
  "packages",
  "fallbacks",
  "src",
  "data.ts",
);

// Parse + re-serialize so the emitted literal is normalized (and so a malformed source fails loudly).
const rows = JSON.parse(readFileSync(SRC, "utf8"));
const body = JSON.stringify(rows, null, 2);

const file = `// GENERATED by scripts/gen-fallbacks-data.ts from the docfonts registry artifact. DO NOT EDIT.
// Source of truth: packages/registry/data/registry/substitution-evidence.json (itself generated from
// records.json). Regenerate after the registry export changes; a drift test enforces the match.
import type { SubstitutionEvidence } from "./types";

export const SUBSTITUTION_EVIDENCE: readonly SubstitutionEvidence[] = ${body};
`;

writeFileSync(OUT, file);
console.log(
  `[gen-fallbacks] wrote data.ts: ${rows.length} rows (${rows.filter((r: { policyAction: string }) => r.policyAction === "substitute").length} substitute).`,
);
