/**
 * Corpus integrity tests. The corpus manifests are generated by scripts/import-corpus.ts and carry
 * the provenance the registry's verdicts ultimately rest on, so these enforce the invariants that
 * make a fileSha256 a trustworthy join key: hashes well-formed and unique, no duplicate logical
 * faces, license provenance present, parsed metadata attached, and NO proprietary family ingested.
 */
import { describe, expect, test } from "bun:test";
import { corpusFaces, loadCorpus } from "./src/index";

const HEX64 = /^[0-9a-f]{64}$/;
const PROPRIETARY = new Set([
  "calibri",
  "cambria",
  "aptos",
  "arial",
  "times new roman",
  "courier new",
  "georgia",
  "verdana",
]);

describe("loadCorpus (open-font corpus manifests)", () => {
  const manifests = loadCorpus();
  const faces = corpusFaces(manifests);

  test("ship-set (5 families/20 faces) + future-direct candidates (Liberation Sans Narrow, 4 faces)", () => {
    const ship = manifests.find(
      (m) => m.corpusId === "current-ship-set-2026-06-03",
    );
    const future = manifests.find(
      (m) => m.corpusId === "future-direct-candidates-2026-06-03",
    );
    expect(ship?.families.length).toBe(5);
    expect(future?.families.map((f) => f.family)).toEqual([
      "Liberation Sans Narrow",
    ]);
    const lsn = future?.families[0];
    expect(lsn?.faces.map((f) => f.styleKey).sort()).toEqual([
      "bold",
      "boldItalic",
      "italic",
      "regular",
    ]);
    expect(lsn?.license).toBe("GPLv2-with-font-exception");
    expect(faces.length).toBe(28); // 20 ship-set + 4 LSN + 4 Gelasio instances
  });

  test("Gelasio instances carry full variable-instance provenance (instancedFrom)", () => {
    const gen = manifests.find(
      (m) => m.corpusId === "generated-instances-2026-06-03",
    );
    const gelasio = gen?.families.find((f) => f.family === "Gelasio");
    expect(gelasio?.faces.length).toBe(4);
    const bold = gelasio?.faces.find((f) => f.styleKey === "bold");
    expect(bold?.instancedFrom).toBeTruthy();
    expect(bold?.instancedFrom?.sourceFileName).toBe("Gelasio[wght].ttf");
    expect(bold?.instancedFrom?.axes.wght).toBe(700);
    expect(bold?.instancedFrom?.sourceFileSha256).toMatch(HEX64);
    expect(bold?.instancedFrom?.tool).toContain("instancer");
    // every Gelasio face is generated, so every one must carry instancedFrom.
    for (const f of gelasio?.faces ?? []) expect(f.instancedFrom).toBeTruthy();
  });

  test("every face fileSha256 is well-formed and globally unique (dedup by hash)", () => {
    const seen = new Set<string>();
    for (const { face } of faces) {
      expect(face.fileSha256).toMatch(HEX64);
      expect(seen.has(face.fileSha256)).toBe(false);
      seen.add(face.fileSha256);
    }
  });

  test("candidateFaceId is globally unique and weight/sha-qualified (future-safe identity)", () => {
    const ids = faces.map(({ face }) => face.candidateFaceId);
    expect(new Set(ids).size).toBe(ids.length);
    // identity carries weight + a sha prefix so multiple weights of one styleKey never collide.
    for (const id of ids) expect(id).toMatch(/#w\d+#[0-9a-f]{8}$/);
  });

  test("every family carries license provenance + a well-formed license-text hash + license URL", () => {
    for (const m of manifests) {
      for (const fam of m.families) {
        expect(fam.license).toBeTruthy();
        expect(fam.licenseSource).toBeTruthy();
        expect(fam.licenseTextSha256).toMatch(HEX64);
        // licenseUrl is the license's URL; sourceUrl is where the font came from - distinct fields.
        expect(fam.licenseUrl).toBeTruthy();
        expect(fam.sourceUrl).toBeTruthy();
        expect(fam.sourceUrl).not.toBe(fam.licenseUrl);
      }
    }
  });

  test("every face has parsed metadata whose fileSha256 matches the face", () => {
    for (const { face } of faces) {
      expect(face.metadata).toBeTruthy();
      expect(face.metadata.fileSha256).toBe(face.fileSha256);
      expect(face.metadata.face.styleKey).toBe(face.styleKey);
    }
  });

  test("no proprietary family is present (the corpus is open fonts only)", () => {
    for (const { face } of faces) {
      expect(PROPRIETARY.has(face.family.toLowerCase())).toBe(false);
    }
  });

  test("each manifest declares a corpusId, source, and retrieval date", () => {
    for (const m of manifests) {
      expect(m.corpusId).toBeTruthy();
      expect(m.source).toBeTruthy();
      expect(m.retrievedDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });
});
