/**
 * Discovery-layer contract tests. The discovery snapshot is the broad SEARCH SPACE (open fonts we can
 * compare against), generated by scripts/import-discovery.ts and committed under data/discovery/. It is
 * NOT the reviewed candidate corpus, so it carries lighter (source-derived) provenance - but it must
 * still be PUBLIC-SAFE (no binaries, no private paths), have stable identity (sha per face), and flag
 * variable fonts explicitly. These tests fail the build if any of that regresses.
 */
import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { DiscoverySnapshot, FontSource } from "./src/index";

const DATA = join(import.meta.dir, "data");
const sources = (
  JSON.parse(readFileSync(join(DATA, "sources.json"), "utf8")) as {
    sources: FontSource[];
  }
).sources;
const snapshot = JSON.parse(
  readFileSync(
    join(DATA, "discovery", "google-fonts-all-files-2026-06-04.json"),
    "utf8",
  ),
) as DiscoverySnapshot;

const SOURCE_TYPES = new Set(["git", "release", "package", "local-artifact"]);
const TRUST = new Set(["discovery", "reviewed", "authoritative"]);
const CATEGORIES = new Set([
  "sans",
  "serif",
  "mono",
  "script",
  "display",
  "symbol",
  "unknown",
]);
const STYLE_KEYS = new Set([
  "regular",
  "bold",
  "italic",
  "boldItalic",
  "other",
]);

describe("source registry (sources.json)", () => {
  it("every source declares id, type, trust, upstream, and license policy", () => {
    expect(sources.length).toBeGreaterThanOrEqual(1);
    for (const s of sources) {
      expect(s.sourceId).toBeTruthy();
      expect(s.name).toBeTruthy();
      expect(SOURCE_TYPES.has(s.type)).toBe(true);
      expect(TRUST.has(s.trust)).toBe(true);
      expect(s.upstreamUrl).toMatch(/^https?:\/\//);
      expect(s.licensePolicy).toBeTruthy();
      expect(s.retrieval).toBeTruthy();
    }
    expect(new Set(sources.map((s) => s.sourceId)).size).toBe(sources.length);
  });
});

describe("discovery snapshot (google-fonts-all-files)", () => {
  it("is pinned to a registered source, dated, and records its acquisition mode", () => {
    expect(sources.some((s) => s.sourceId === snapshot.sourceId)).toBe(true);
    expect(snapshot.sourceUrl).toMatch(/^https?:\/\//);
    expect(snapshot.retrievedDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(snapshot.faceCount).toBe(snapshot.faces.length);
    expect(snapshot.faces.length).toBeGreaterThan(1000);
    // honest about HOW it was obtained; the bootstrap path is unpinned by design.
    expect(snapshot.acquisition).toBeTruthy();
    if (snapshot.acquisition === "local_bootstrap") {
      expect(snapshot.sourceCommit).toBeUndefined();
    }
  });

  it("every face has stable identity + explicit license basis + parsed facts", () => {
    for (const f of snapshot.faces) {
      expect(f.fileSha256).toMatch(/^[0-9a-f]{64}$/);
      expect(f.family).toBeTruthy();
      expect(STYLE_KEYS.has(f.styleKey)).toBe(true);
      expect(Number.isFinite(f.weight)).toBe(true);
      expect(CATEGORIES.has(f.category)).toBe(true);
      expect(f.latinCoverage).toBeGreaterThanOrEqual(0);
      expect(f.latinCoverage).toBeLessThanOrEqual(1);
      expect(f.license).toBeTruthy();
      expect(f.licenseBasis).toBeTruthy(); // license is inferred, but the BASIS must be explicit
      expect(f.repoPath).toBeTruthy();
      expect(f.rawUrl).toMatch(/^https?:\/\//);
    }
  });

  it("hashes are unique, and any duplicates are REPORTED not hidden", () => {
    const shas = snapshot.faces.map((f) => f.fileSha256);
    expect(new Set(shas).size).toBe(shas.length); // collapsed during import
    expect(Array.isArray(snapshot.duplicates)).toBe(true);
    // faceCount + collapsed duplicates account for every input row, so nothing is silently dropped.
    for (const d of snapshot.duplicates) {
      expect(d.fileSha256).toMatch(/^[0-9a-f]{64}$/);
      expect(d.count).toBeGreaterThan(1);
    }
  });

  it("flags variable fonts explicitly (axes present iff isVariable)", () => {
    const variable = snapshot.faces.filter((f) => f.isVariable);
    expect(variable.length).toBeGreaterThan(0);
    for (const f of snapshot.faces) {
      expect(typeof f.isVariable).toBe("boolean");
      if (f.axes) {
        expect(f.isVariable).toBe(true);
        expect(f.axes.length).toBeGreaterThan(0);
      }
    }
  });
});

describe("public-repo safety", () => {
  it("commits no binaries and leaks no private/local paths", () => {
    const blob = `${JSON.stringify(snapshot)}\n${JSON.stringify(sources)}`;
    for (const marker of ["/Users/", "/Applications/", "/System/", "localPath"])
      expect(blob.includes(marker)).toBe(false);
    // a font face is a POINTER (sha + re-fetch url), never embedded bytes.
    expect(blob).not.toMatch(/"bytes"\s*:/);
  });
});
