/**
 * Contract tests for the two record sources:
 *   - loadRecords()     -> the CANONICAL registry (data/registry/records.json), now GENERATED by
 *                          scripts/import-research.ts. Validated against the generated measurement set
 *                          (ref resolution + layout-gate<->proof), so a dangling ref fails the build.
 *   - loadSeedRecords() -> the interim research seed the site still renders from until it switches to
 *                          loadRecords(). Kept distinct; not a fallback.
 */

import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  findByOriginal,
  loadRecords,
  loadSeedRecords,
  type MeasurementKind,
  validateRecords,
  withVerdict,
} from "./src/index";

/** Load the generated measurement index (id + kind) so records can be validated for ref resolution. */
function measurementIndex(): {
  measurementId: string;
  kind: MeasurementKind;
}[] {
  const dir = join(import.meta.dir, "data", "measurements");
  const out: { measurementId: string; kind: MeasurementKind }[] = [];
  for (const f of readdirSync(dir)) {
    if (!f.endsWith(".json")) continue;
    const arr = JSON.parse(readFileSync(join(dir, f), "utf8")) as {
      measurementId: string;
      kind: MeasurementKind;
    }[];
    for (const m of arr)
      out.push({ measurementId: m.measurementId, kind: m.kind });
  }
  return out;
}

describe("loadRecords (canonical generated registry)", () => {
  const records = loadRecords();

  test("is generated + non-empty", () => {
    expect(records.length).toBeGreaterThanOrEqual(7);
  });

  test("validates against the schema AND the generated measurement set (no dangling refs)", () => {
    const res = validateRecords(records, { measurements: measurementIndex() });
    expect(res.errors).toEqual([]);
    expect(res.ok).toBe(true);
  });

  test("every record is backed by at least one measurement", () => {
    for (const r of records)
      expect(r.measurementRefs.length).toBeGreaterThanOrEqual(1);
  });

  test("Calibri is a metric_safe Carlito substitute", () => {
    const [calibri] = findByOriginal(records, "Calibri");
    expect(calibri?.verdict).toBe("metric_safe");
    expect(calibri?.candidate?.candidateFamily).toBe("Carlito");
  });

  test("Aptos is no_substitute with no candidate, no record-level advance", () => {
    const [aptos] = findByOriginal(records, "Aptos");
    expect(aptos?.verdict).toBe("no_substitute");
    expect(aptos?.candidate ?? null).toBeNull();
    expect(aptos?.advance).toBeUndefined();
  });

  test("Consolas is cell_width_only (the curated verdict, not a prose guess)", () => {
    const [consolas] = findByOriginal(records, "Consolas");
    expect(consolas?.verdict).toBe("cell_width_only");
  });

  test("every metric_safe record has a candidate and an in-threshold advance", () => {
    for (const r of withVerdict(records, "metric_safe")) {
      expect(r.candidate?.candidateFamily).toBeTruthy();
      expect(r.advance?.meanDelta ?? 1).toBeLessThanOrEqual(0.005);
    }
  });

  test("no_substitute records never carry a candidate", () => {
    for (const r of withVerdict(records, "no_substitute")) {
      expect(r.candidate ?? null).toBeNull();
    }
  });

  test("a layout=pass gate is backed by a face_aggregate or live_layout proof ref", () => {
    for (const r of records) {
      if (r.gates.layout !== "pass") continue;
      const backed = r.measurementRefs.some(
        (ref) =>
          ref.includes("#face_aggregate#") || ref.includes("#live_layout#"),
      );
      expect(backed).toBe(true);
    }
  });
});

describe("loadSeedRecords (interim research seed; site still uses it pre-switch)", () => {
  const records = loadSeedRecords();

  test("is present and schema-valid", () => {
    expect(records.length).toBeGreaterThanOrEqual(9);
    expect(validateRecords(records)).toEqual({ ok: true, errors: [] });
  });
});
